version: '3'
services:
  mariadb:
    image: mariadb
    container_name: 'nest_todo_mariadb'
    environment:
      MARIADB_ROOT_PASSWORD: 'abc123'
      MARIADB_DATABASE: 'nest_todo'
    ports:
      - 3306:3306
    restart: always
  redis:
    image: redis
    container_name: 'nest_todo_redis'
    ports:
      - 6379:6379
    restart: always
